### ISSUE TITLE
Corrections

### ISSUE THREAD

**Issue by abelsiqueira** [Egmara/AugLag.jl#1]
- Docstrings (https://github.com/Egmara/Augmented-Lagrangian/blob/master/ALModel.jl#L1) are used right before a function (or structure) to define the function's help;
- Use `dot(x, y)`, not `x' * y`;
- Put spaces between operations: `x * y` instead of `x*y`;
- Here (https://github.com/Egmara/Augmented-Lagrangian/blob/master/al.jl#L29) it should be something like `al_nlp = Augmented...(nlp, y, mu)`;
- Missing API:
  - [ ] `grad`
  - [ ] `hess`
  - [ ] `hprod`
  - [ ] `hess_coord`

**Comment by dpo** [comment]
Note that you need only implement the in-place methods now: `grad!()`, `hess_structure!()`, `hess_coord!()`, etc.

**Comment by Egmara** [comment]
Implemented methods: `grad!()`,` hess_structure()`, `hess_structure!()`, `hess_coord()`, `hess_coord!()`. NLPModels codes helped me.
